### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/pleroma/commit/49245100af7c4d2b8994e860004d57fa8f7b24e6#commitcomment-91181219

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/pleroma/commit/7a5933ed571d36fbef0e585c76ca9ce91d84f861

Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

### CODE REVIEW

**Comment by jsoref** [comment]
Sorry, it's much easier for me to make PRs via GitHub... I'll try to send it via GitLab...

**Comment by minibikini** [comment]
Thank you @jsoref!

i

**Comment by jsoref** [comment]
For the record, I tried https://git.pleroma.social/jsoref/pleroma/-/jobs/224364 and I have no idea what it's thinking...

**Comment by minibikini** [comment]
Not sure what's going on there. Try to contact maintainers on IRC: 
`#pleroma` and `#pleroma-de` on `libera.chat`
Webchat is available at https://irc.pleroma.social/

**Comment by jsoref** [comment]
fwiw, the webchat doesn't work:
> You are banned from this server- Your host is listed on DroneBL. Visit http://dronebl.org/lookup?ip=163.237.247.127 to request removal. Email bans@libera.chat for additional assistance. (2022/12/14 11.37)

**Pull request closed without merging**
